%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Youssef Ahmed\Aviation\Live scripts\session_5\LDR_calebration.csv
%
% Auto-generated by MATLAB on 04-Feb-2026 22:37:26

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Klux", "ArduinoOutput", "Volt"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
LDRcalebration = readtable("C:\Youssef Ahmed\Aviation\Live scripts\session_5\LDR_calebration.csv", opts);


%% Clear temporary variables
clear opts